os: linux
dist: bionic

language: python

cache:
  directories:
  - $HOME/.cache/pip

install:
- pip install mkdocs
- pip install markdown-headdown
- pip install pymdown-extensions
- pip install pyembed-markdown
- pip install mdx_include
- pip install markdown-iconfonts

script:
- ./.travis/build.sh
