os: linux
dist: bionic

git:
  depth: 3

language: python
python:
- '3.8'

cache:
  directories:
  - $HOME/.cache/pip

install:
- >-
  pip install
  mkdocs
  markdown-headdown
  pymdown-extensions
  pyembed-markdown
  mdx_include
  markdown-iconfonts

script:
- mkdocs build --clean --verbose

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  on:
    repo: remal/remal.github.io
    branch: master
