os: linux
dist: bionic

language: python

cache:
  directories:
  - $HOME/.cache/pip

install:
- >-
  pip install
  mkdocs
  markdown-headdown
  pymdown-extensions
  pyembed-markdown
  mdx_include
  markdown-iconfonts

script:
- echo 1
