os: linux
dist: bionic

git:
  depth: 3

language: python
python:
- '3.8'

cache:
  directories:
  - $HOME/.cache/pip

install:
- >-
  pip install
  mkdocs
  markdown-headdown
  pymdown-extensions
  pyembed-markdown
  mdx_include
  markdown-iconfonts

script:
- echo 1
